volumes:
  letsencrypt:
    name: letsencrypt

services:
  traefik-reverse-proxy:
    image: traefik-reverse-proxy-image
    pull_policy: never

    build:
      context: .
      dockerfile: ./Dockerfile

    volumes:
      - ./letsencrypt:/letsencrypt

    entrypoint: /entrypoint.sh

    command:
      - "--api.dashboard=true"
      - "--api.insecure=false"

      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.websecure.address=:443"
      - "--entrypoints.websecure.asDefault=true"
      - "--entrypoints.websecure.http.tls.certResolver=tlsResolver"

      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.network=my-external-network"

      - "--accessLog.filePath=/logs/access.log"
      
      - "--log.filePath=/logs/traefik.log"
      - "--log.level=DEBUG"

      
      - "--tracing=true"
      - "--tracing.addinternals"

      ##############################################################################################
      # Enable ACME (Let's Encrypt): automatic SSL.


      ##############################################################################################
      # dns challenge
      ##############################################################################################
      # - "--certificatesresolvers.dnsResolver.acme.dnschallenge=true"
      # - "--certificatesresolvers.dnsResolver.acme.dnschallenge.provider=ovh"
      # - "--certificatesresolvers.dnsResolver.acme.dnschallenge.disablePropagationCheck=true"
      # - "--certificatesresolvers.dnsResolver.acme.dnschallenge.delayBeforeCheck=60"
      # - "--certificatesresolvers.dnsResolver.acme.email=/run/secrets/cert_contact_email"
      # - "--certificatesresolvers.dnsResolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      # #- --certificatesresolvers.dnsResolver.acme.dnschallenge.resolvers=8.8.8.8
      # - "--certificatesresolvers.dnsResolver.acme.storage=/letsencrypt/acme.json"
      ##############################################################################################



      
      ##############################################################################################
      # tlschallenge challenge
      ##############################################################################################
      # Email address used for registration.
      #
      # Required
      #
      #- "--certificatesresolvers.tlsResolver.acme.email=/secrets/cert_contact_email"
      - "--certificatesresolvers.tlsResolver.acme.email=contact@my-domain.com"

      # File or key used for certificates storage.
      #
      # Required
      #
      - "--certificatesresolvers.tlsResolver.acme.storage=/letsencrypt/acme.json"

      # CA server to use.
      # Uncomment the line to use Let's Encrypt's staging server,
      # leave commented to go to prod.
      #
      # Optional
      # Default: "https://acme-v02.api.letsencrypt.org/directory"
      # Staging: "https://acme-staging-v02.api.letsencrypt.org/directory"
      #
      - "--certificatesresolvers.tlsResolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"

      # The certificates' duration in hours.
      # It defaults to 2160 (90 days) to follow Let's Encrypt certificates' duration.
      #
      # Optional
      # Default: 2160
      #
      - "--certificatesresolvers.tlsResolver.acme.certificatesDuration=2160"

      # Use a TLS-ALPN-01 ACME challenge.
      #
      # Optional (but recommended)
      #
      - "--certificatesresolvers.tlsResolver.acme.tlschallenge=true"
      ##############################################################################################



      ##############################################################################################
      # http challenge
      ##############################################################################################
      # # - "--certificatesresolvers.httpCertificateResolver.acme.httpchallenge=true"
      # # - "--certificatesresolvers.httpCertificateResolver.acme.httpchallenge.entrypoint=web"
      # # - "--certificatesresolvers.httpCertificateResolver.acme.email=/secrets/cert_contact_email"
      # # - "--certificatesresolvers.httpCertificateResolver.acme.storage=/letsencrypt/acme.json"
      ##############################################################################################

    restart: always

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-reverse-proxy.middlewares=dashboard-auth"
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=${TRAEFIK_CREDENTIALS}"